export const STATUS_MAP = {
    APPROVED: { label: 'Đã duyệt', tw: 'bg-green-100 text-green-700' },
    PENDING: { label: 'Chờ duyệt', tw: 'bg-amber-100 text-amber-700' },
    REJECTED: { label: 'Từ chối', tw: 'bg-red-100 text-red-700' },
    DRAFT: { label: 'Bản nháp', tw: 'bg-slate-100 text-slate-600' },
    IN_PROGRESS: { label: 'Đang thực hiện', tw: 'bg-blue-100 text-blue-700' },
    SUBMITTED: { label: 'Đã nộp', tw: 'bg-cyan-100 text-cyan-700' },
    DEFENDED: { label: 'Đã bảo vệ', tw: 'bg-purple-100 text-purple-700' },
    COMPLETED: { label: 'Hoàn thành', tw: 'bg-emerald-100 text-emerald-700' },
    DROPPED: { label: 'Đã hủy', tw: 'bg-rose-100 text-rose-700' },
    WITHDRAWN: { label: 'Đã rút', tw: 'bg-orange-100 text-orange-700' },
    OPEN: { label: 'Chưa nộp', tw: 'bg-amber-100 text-amber-700' },
    REVISION: { label: 'Yêu cầu sửa', tw: 'bg-orange-100 text-orange-700' },
    OVERDUE: { label: 'Trễ hạn', tw: 'bg-red-100 text-red-700' },
    ONGOING: { label: 'Đang diễn ra', tw: 'bg-green-100 text-green-700' },
    REGISTRATION: { label: 'Đang đăng ký', tw: 'bg-orange-100 text-orange-700' },
    UPCOMING: { label: 'Sắp tới', tw: 'bg-blue-100 text-blue-700' },
    DEFENSE: { label: 'Bảo vệ', tw: 'bg-purple-100 text-purple-700' },
    active: { label: 'Hoạt động', tw: 'bg-emerald-100 text-emerald-700' },
    inactive: { label: 'Vô hiệu', tw: 'bg-red-100 text-red-700' },
};
